// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // ContactType
        ///<summary>
        /// Lookup table containing the types of business entity contacts.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class ContactType
    {

        ///<summary>
        /// Primary key for ContactType records.
        ///</summary>
        public int? ContactTypeId { get; set; } // ContactTypeID (Primary key)

        ///<summary>
        /// Contact type description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child BusinessEntityContacts where [BusinessEntityContact].[ContactTypeID] point to this entity (FK_BusinessEntityContact_ContactType_ContactTypeID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; } // BusinessEntityContact.FK_BusinessEntityContact_ContactType_ContactTypeID

        public ContactType()
        {
            ModifiedDate = System.DateTime.Now;
            BusinessEntityContacts = new System.Collections.Generic.List<BusinessEntityContact>();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
