// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    public partial interface IAdventureWorksDB : System.IDisposable
    {
        System.Data.Entity.DbSet<Address> Addresses { get; set; } // Address
        System.Data.Entity.DbSet<AddressType> AddressTypes { get; set; } // AddressType
        System.Data.Entity.DbSet<AwBuildVersion> AwBuildVersions { get; set; } // AWBuildVersion
        System.Data.Entity.DbSet<BillOfMaterial> BillOfMaterials { get; set; } // BillOfMaterials
        System.Data.Entity.DbSet<BusinessEntity> BusinessEntities { get; set; } // BusinessEntity
        System.Data.Entity.DbSet<BusinessEntityAddress> BusinessEntityAddresses { get; set; } // BusinessEntityAddress
        System.Data.Entity.DbSet<BusinessEntityContact> BusinessEntityContacts { get; set; } // BusinessEntityContact
        System.Data.Entity.DbSet<ContactType> ContactTypes { get; set; } // ContactType
        System.Data.Entity.DbSet<CountryRegion> CountryRegions { get; set; } // CountryRegion
        System.Data.Entity.DbSet<CountryRegionCurrency> CountryRegionCurrencies { get; set; } // CountryRegionCurrency
        System.Data.Entity.DbSet<CreditCard> CreditCards { get; set; } // CreditCard
        System.Data.Entity.DbSet<Culture> Cultures { get; set; } // Culture
        System.Data.Entity.DbSet<Currency> Currencies { get; set; } // Currency
        System.Data.Entity.DbSet<CurrencyRate> CurrencyRates { get; set; } // CurrencyRate
        System.Data.Entity.DbSet<Customer> Customers { get; set; } // Customer
        System.Data.Entity.DbSet<DatabaseLog> DatabaseLogs { get; set; } // DatabaseLog
        System.Data.Entity.DbSet<Department> Departments { get; set; } // Department
        System.Data.Entity.DbSet<Document> Documents { get; set; } // Document
        System.Data.Entity.DbSet<EmailAddress> EmailAddresses { get; set; } // EmailAddress
        System.Data.Entity.DbSet<Employee> Employees { get; set; } // Employee
        System.Data.Entity.DbSet<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; } // EmployeeDepartmentHistory
        System.Data.Entity.DbSet<EmployeePayHistory> EmployeePayHistories { get; set; } // EmployeePayHistory
        System.Data.Entity.DbSet<ErrorLog> ErrorLogs { get; set; } // ErrorLog
        System.Data.Entity.DbSet<Illustration> Illustrations { get; set; } // Illustration
        System.Data.Entity.DbSet<JobCandidate> JobCandidates { get; set; } // JobCandidate
        System.Data.Entity.DbSet<Location> Locations { get; set; } // Location
        System.Data.Entity.DbSet<Password> Passwords { get; set; } // Password
        System.Data.Entity.DbSet<Person> People { get; set; } // Person
        System.Data.Entity.DbSet<PersonCreditCard> PersonCreditCards { get; set; } // PersonCreditCard
        System.Data.Entity.DbSet<PersonPhone> PersonPhones { get; set; } // PersonPhone
        System.Data.Entity.DbSet<PhoneNumberType> PhoneNumberTypes { get; set; } // PhoneNumberType
        System.Data.Entity.DbSet<Product> Products { get; set; } // Product
        System.Data.Entity.DbSet<ProductCategory> ProductCategories { get; set; } // ProductCategory
        System.Data.Entity.DbSet<ProductCostHistory> ProductCostHistories { get; set; } // ProductCostHistory
        System.Data.Entity.DbSet<ProductDescription> ProductDescriptions { get; set; } // ProductDescription
        System.Data.Entity.DbSet<ProductDocument> ProductDocuments { get; set; } // ProductDocument
        System.Data.Entity.DbSet<ProductInventory> ProductInventories { get; set; } // ProductInventory
        System.Data.Entity.DbSet<ProductListPriceHistory> ProductListPriceHistories { get; set; } // ProductListPriceHistory
        System.Data.Entity.DbSet<ProductModel> ProductModels { get; set; } // ProductModel
        System.Data.Entity.DbSet<ProductModelIllustration> ProductModelIllustrations { get; set; } // ProductModelIllustration
        System.Data.Entity.DbSet<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; } // ProductModelProductDescriptionCulture
        System.Data.Entity.DbSet<ProductPhoto> ProductPhotos { get; set; } // ProductPhoto
        System.Data.Entity.DbSet<ProductProductPhoto> ProductProductPhotos { get; set; } // ProductProductPhoto
        System.Data.Entity.DbSet<ProductReview> ProductReviews { get; set; } // ProductReview
        System.Data.Entity.DbSet<ProductSubcategory> ProductSubcategories { get; set; } // ProductSubcategory
        System.Data.Entity.DbSet<ProductVendor> ProductVendors { get; set; } // ProductVendor
        System.Data.Entity.DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } // PurchaseOrderDetail
        System.Data.Entity.DbSet<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; } // PurchaseOrderHeader
        System.Data.Entity.DbSet<SalesOrderDetail> SalesOrderDetails { get; set; } // SalesOrderDetail
        System.Data.Entity.DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; } // SalesOrderHeader
        System.Data.Entity.DbSet<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; } // SalesOrderHeaderSalesReason
        System.Data.Entity.DbSet<SalesPerson> SalesPeople { get; set; } // SalesPerson
        System.Data.Entity.DbSet<SalesPersonQuotaHistory> SalesPersonQuotaHistories { get; set; } // SalesPersonQuotaHistory
        System.Data.Entity.DbSet<SalesReason> SalesReasons { get; set; } // SalesReason
        System.Data.Entity.DbSet<SalesTaxRate> SalesTaxRates { get; set; } // SalesTaxRate
        System.Data.Entity.DbSet<SalesTerritory> SalesTerritories { get; set; } // SalesTerritory
        System.Data.Entity.DbSet<SalesTerritoryHistory> SalesTerritoryHistories { get; set; } // SalesTerritoryHistory
        System.Data.Entity.DbSet<ScrapReason> ScrapReasons { get; set; } // ScrapReason
        System.Data.Entity.DbSet<Shift> Shifts { get; set; } // Shift
        System.Data.Entity.DbSet<ShipMethod> ShipMethods { get; set; } // ShipMethod
        System.Data.Entity.DbSet<ShoppingCartItem> ShoppingCartItems { get; set; } // ShoppingCartItem
        System.Data.Entity.DbSet<SpecialOffer> SpecialOffers { get; set; } // SpecialOffer
        System.Data.Entity.DbSet<SpecialOfferProduct> SpecialOfferProducts { get; set; } // SpecialOfferProduct
        System.Data.Entity.DbSet<StateProvince> StateProvinces { get; set; } // StateProvince
        System.Data.Entity.DbSet<Store> Stores { get; set; } // Store
        System.Data.Entity.DbSet<TransactionHistory> TransactionHistories { get; set; } // TransactionHistory
        System.Data.Entity.DbSet<TransactionHistoryArchive> TransactionHistoryArchives { get; set; } // TransactionHistoryArchive
        System.Data.Entity.DbSet<UnitMeasure> UnitMeasures { get; set; } // UnitMeasure
        System.Data.Entity.DbSet<VAdditionalContactInfo> VAdditionalContactInfos { get; set; } // vAdditionalContactInfo
        System.Data.Entity.DbSet<VEmployee> VEmployees { get; set; } // vEmployee
        System.Data.Entity.DbSet<VEmployeeDepartment> VEmployeeDepartments { get; set; } // vEmployeeDepartment
        System.Data.Entity.DbSet<VEmployeeDepartmentHistory> VEmployeeDepartmentHistories { get; set; } // vEmployeeDepartmentHistory
        System.Data.Entity.DbSet<Vendor> Vendors { get; set; } // Vendor
        System.Data.Entity.DbSet<VIndividualCustomer> VIndividualCustomers { get; set; } // vIndividualCustomer
        System.Data.Entity.DbSet<VJobCandidate> VJobCandidates { get; set; } // vJobCandidate
        System.Data.Entity.DbSet<VJobCandidateEducation> VJobCandidateEducations { get; set; } // vJobCandidateEducation
        System.Data.Entity.DbSet<VJobCandidateEmployment> VJobCandidateEmployments { get; set; } // vJobCandidateEmployment
        System.Data.Entity.DbSet<VPersonDemographic> VPersonDemographics { get; set; } // vPersonDemographics
        System.Data.Entity.DbSet<VProductAndDescription> VProductAndDescriptions { get; set; } // vProductAndDescription
        System.Data.Entity.DbSet<VProductModelCatalogDescription> VProductModelCatalogDescriptions { get; set; } // vProductModelCatalogDescription
        System.Data.Entity.DbSet<VProductModelInstruction> VProductModelInstructions { get; set; } // vProductModelInstructions
        System.Data.Entity.DbSet<VSalesPerson> VSalesPeople { get; set; } // vSalesPerson
        System.Data.Entity.DbSet<VSalesPersonSalesByFiscalYear> VSalesPersonSalesByFiscalYears { get; set; } // vSalesPersonSalesByFiscalYears
        System.Data.Entity.DbSet<VStateProvinceCountryRegion> VStateProvinceCountryRegions { get; set; } // vStateProvinceCountryRegion
        System.Data.Entity.DbSet<VStoreWithAddress> VStoreWithAddresses { get; set; } // vStoreWithAddresses
        System.Data.Entity.DbSet<VStoreWithContact> VStoreWithContacts { get; set; } // vStoreWithContacts
        System.Data.Entity.DbSet<VStoreWithDemographic> VStoreWithDemographics { get; set; } // vStoreWithDemographics
        System.Data.Entity.DbSet<VVendorWithAddress> VVendorWithAddresses { get; set; } // vVendorWithAddresses
        System.Data.Entity.DbSet<VVendorWithContact> VVendorWithContacts { get; set; } // vVendorWithContacts
        System.Data.Entity.DbSet<WorkOrder> WorkOrders { get; set; } // WorkOrder
        System.Data.Entity.DbSet<WorkOrderRouting> WorkOrderRoutings { get; set; } // WorkOrderRouting

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<UspGetBillOfMaterialsReturnModel> UspGetBillOfMaterials(int? startProductId, System.DateTime? checkDate);
        System.Collections.Generic.List<UspGetBillOfMaterialsReturnModel> UspGetBillOfMaterials(int? startProductId, System.DateTime? checkDate, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<UspGetBillOfMaterialsReturnModel>> UspGetBillOfMaterialsAsync(int? startProductId, System.DateTime? checkDate);

        System.Collections.Generic.List<UspGetEmployeeManagersReturnModel> UspGetEmployeeManagers(int? businessEntityId);
        System.Collections.Generic.List<UspGetEmployeeManagersReturnModel> UspGetEmployeeManagers(int? businessEntityId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<UspGetEmployeeManagersReturnModel>> UspGetEmployeeManagersAsync(int? businessEntityId);

        System.Collections.Generic.List<UspGetManagerEmployeesReturnModel> UspGetManagerEmployees(int? businessEntityId);
        System.Collections.Generic.List<UspGetManagerEmployeesReturnModel> UspGetManagerEmployees(int? businessEntityId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<UspGetManagerEmployeesReturnModel>> UspGetManagerEmployeesAsync(int? businessEntityId);

        System.Collections.Generic.List<UspGetWhereUsedProductIdReturnModel> UspGetWhereUsedProductId(int? startProductId, System.DateTime? checkDate);
        System.Collections.Generic.List<UspGetWhereUsedProductIdReturnModel> UspGetWhereUsedProductId(int? startProductId, System.DateTime? checkDate, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<UspGetWhereUsedProductIdReturnModel>> UspGetWhereUsedProductIdAsync(int? startProductId, System.DateTime? checkDate);

        int UspLogError(out int? errorLogId);
        // UspLogErrorAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspPrintError();
        // UspPrintErrorAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspSearchCandidateResumes(string searchString, bool? useInflectional, bool? useThesaurus, int? language);
        // UspSearchCandidateResumesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspUpdateEmployeeHireInfo(int? businessEntityId, string jobTitle, System.DateTime? hireDate, System.DateTime? rateChangeDate, decimal? rate, byte? payFrequency, bool? currentFlag);
        // UspUpdateEmployeeHireInfoAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspUpdateEmployeeLogin(int? businessEntityId, System.Data.Entity.Hierarchy.HierarchyId organizationNode, string loginId, string jobTitle, System.DateTime? hireDate, bool? currentFlag);
        // UspUpdateEmployeeLoginAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspUpdateEmployeePersonalInfo(int? businessEntityId, string nationalIdNumber, System.DateTime? birthDate, string maritalStatus, string gender);
        // UspUpdateEmployeePersonalInfoAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

    }


}
// </auto-generated>
