// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // Illustration
        ///<summary>
        /// Bicycle assembly diagrams.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class Illustration
    {

        ///<summary>
        /// Primary key for Illustration records.
        ///</summary>
        public int? IllustrationId { get; set; } // IllustrationID (Primary key)

        ///<summary>
        /// Illustrations used in manufacturing instructions. Stored as XML.
        ///</summary>
        public string Diagram { get; set; } // Diagram

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child ProductModelIllustrations where [ProductModelIllustration].[IllustrationID] point to this entity (FK_ProductModelIllustration_Illustration_IllustrationID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; } // ProductModelIllustration.FK_ProductModelIllustration_Illustration_IllustrationID

        public Illustration()
        {
            ModifiedDate = System.DateTime.Now;
            ProductModelIllustrations = new System.Collections.Generic.List<ProductModelIllustration>();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
