// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // ProductModelIllustration
        ///<summary>
        /// Cross-reference table mapping product models and illustrations.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class ProductModelIllustration
    {

        ///<summary>
        /// Primary key. Foreign key to ProductModel.ProductModelID.
        ///</summary>
        public int? ProductModelId { get; set; } // ProductModelID (Primary key)

        ///<summary>
        /// Primary key. Foreign key to Illustration.IllustrationID.
        ///</summary>
        public int? IllustrationId { get; set; } // IllustrationID (Primary key)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent Illustration pointed by [ProductModelIllustration].([IllustrationId]) (FK_ProductModelIllustration_Illustration_IllustrationID)
        /// </summary>
        public virtual Illustration Illustration { get; set; } // FK_ProductModelIllustration_Illustration_IllustrationID

        /// <summary>
        /// Parent ProductModel pointed by [ProductModelIllustration].([ProductModelId]) (FK_ProductModelIllustration_ProductModel_ProductModelID)
        /// </summary>
        public virtual ProductModel ProductModel { get; set; } // FK_ProductModelIllustration_ProductModel_ProductModelID

        public ProductModelIllustration()
        {
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
