// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // ProductDocument
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class ProductDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProductDocument>
    {
        public ProductDocumentConfiguration() : this("Production")
        {
        }

        public ProductDocumentConfiguration(string schema)
        {
            ToTable("ProductDocument", schema);
            HasKey(x => new { x.ProductId, x.DocumentNode });

            Property(x => x.ProductId).HasColumnName(@"ProductID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DocumentNode).HasColumnName(@"DocumentNode").HasColumnType("hierarchyid").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Document).WithMany(b => b.ProductDocuments).HasForeignKey(c => c.DocumentNode).WillCascadeOnDelete(false); // FK_ProductDocument_Document_DocumentNode
            HasRequired(a => a.Product).WithMany(b => b.ProductDocuments).HasForeignKey(c => c.ProductId).WillCascadeOnDelete(false); // FK_ProductDocument_Product_ProductID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
