// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // SalesTerritory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class SalesTerritoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesTerritory>
    {
        public SalesTerritoryConfiguration() : this("Sales")
        {
        }

        public SalesTerritoryConfiguration(string schema)
        {
            ToTable("SalesTerritory", schema);
            HasKey(x => x.TerritoryId);

            Property(x => x.TerritoryId).HasColumnName(@"TerritoryID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.CountryRegionCode).HasColumnName(@"CountryRegionCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.Group).HasColumnName(@"Group").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.SalesYtd).HasColumnName(@"SalesYTD").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.SalesLastYear).HasColumnName(@"SalesLastYear").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.CostYtd).HasColumnName(@"CostYTD").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.CostLastYear).HasColumnName(@"CostLastYear").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.CountryRegion).WithMany(b => b.SalesTerritories).HasForeignKey(c => c.CountryRegionCode).WillCascadeOnDelete(false); // FK_SalesTerritory_CountryRegion_CountryRegionCode
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
