// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // SalesReason
        ///<summary>
        /// Lookup table of customer purchase reasons.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class SalesReason
    {

        ///<summary>
        /// Primary key for SalesReason records.
        ///</summary>
        public int? SalesReasonId { get; set; } // SalesReasonID (Primary key)

        ///<summary>
        /// Sales reason description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Category the sales reason belongs to.
        ///</summary>
        public string ReasonType { get; set; } // ReasonType (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesOrderHeaderSalesReasons where [SalesOrderHeaderSalesReason].[SalesReasonID] point to this entity (FK_SalesOrderHeaderSalesReason_SalesReason_SalesReasonID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; } // SalesOrderHeaderSalesReason.FK_SalesOrderHeaderSalesReason_SalesReason_SalesReasonID

        public SalesReason()
        {
            ModifiedDate = System.DateTime.Now;
            SalesOrderHeaderSalesReasons = new System.Collections.Generic.List<SalesOrderHeaderSalesReason>();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
