// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // ScrapReason
        ///<summary>
        /// Manufacturing failure reasons lookup table.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class ScrapReason
    {

        ///<summary>
        /// Primary key for ScrapReason records.
        ///</summary>
        public short ScrapReasonId { get; set; } // ScrapReasonID (Primary key)

        ///<summary>
        /// Failure description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child WorkOrders where [WorkOrder].[ScrapReasonID] point to this entity (FK_WorkOrder_ScrapReason_ScrapReasonID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkOrder> WorkOrders { get; set; } // WorkOrder.FK_WorkOrder_ScrapReason_ScrapReasonID

        public ScrapReason()
        {
            ModifiedDate = System.DateTime.Now;
            WorkOrders = new System.Collections.Generic.List<WorkOrder>();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
