// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // UnitMeasure
        ///<summary>
        /// Unit of measure lookup table.
        ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class UnitMeasure
    {

        ///<summary>
        /// Primary key.
        ///</summary>
        public string UnitMeasureCode { get; set; } // UnitMeasureCode (Primary key) (length: 3)

        ///<summary>
        /// Unit of measure description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child BillOfMaterials where [BillOfMaterials].[UnitMeasureCode] point to this entity (FK_BillOfMaterials_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BillOfMaterial> BillOfMaterials { get; set; } // BillOfMaterials.FK_BillOfMaterials_UnitMeasure_UnitMeasureCode

        /// <summary>
        /// Child Products where [Product].[SizeUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_SizeUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products_SizeUnitMeasureCode { get; set; } // Product.FK_Product_UnitMeasure_SizeUnitMeasureCode

        /// <summary>
        /// Child Products where [Product].[WeightUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_WeightUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products_WeightUnitMeasureCode { get; set; } // Product.FK_Product_UnitMeasure_WeightUnitMeasureCode

        /// <summary>
        /// Child ProductVendors where [ProductVendor].[UnitMeasureCode] point to this entity (FK_ProductVendor_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProductVendor> ProductVendors { get; set; } // ProductVendor.FK_ProductVendor_UnitMeasure_UnitMeasureCode

        public UnitMeasure()
        {
            ModifiedDate = System.DateTime.Now;
            BillOfMaterials = new System.Collections.Generic.List<BillOfMaterial>();
            Products_SizeUnitMeasureCode = new System.Collections.Generic.List<Product>();
            Products_WeightUnitMeasureCode = new System.Collections.Generic.List<Product>();
            ProductVendors = new System.Collections.Generic.List<ProductVendor>();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
