// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class UspGetEmployeeManagersReturnModel
    {
        public System.Int32? RecursionLevel { get; set; }
        public System.Int32? BusinessEntityID { get; set; }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public System.String OrganizationNode { get; set; }
        public System.String ManagerFirstName { get; set; }
        public System.String ManagerLastName { get; set; }
    }

}
// </auto-generated>
