// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vAdditionalContactInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VAdditionalContactInfo
    {
        public int? BusinessEntityId { get; set; } // BusinessEntityID (Primary key)
        public string FirstName { get; set; } // FirstName (Primary key) (length: 50)
        public string MiddleName { get; set; } // MiddleName (length: 50)
        public string LastName { get; set; } // LastName (Primary key) (length: 50)
        public string TelephoneNumber { get; set; } // TelephoneNumber (length: 50)
        public string TelephoneSpecialInstructions { get; set; } // TelephoneSpecialInstructions
        public string Street { get; set; } // Street (length: 50)
        public string City { get; set; } // City (length: 50)
        public string StateProvince { get; set; } // StateProvince (length: 50)
        public string PostalCode { get; set; } // PostalCode (length: 50)
        public string CountryRegion { get; set; } // CountryRegion (length: 50)
        public string HomeAddressSpecialInstructions { get; set; } // HomeAddressSpecialInstructions
        public string EMailAddress { get; set; } // EMailAddress (length: 128)
        public string EMailSpecialInstructions { get; set; } // EMailSpecialInstructions
        public string EMailTelephoneNumber { get; set; } // EMailTelephoneNumber (length: 50)
        public System.Guid Rowguid { get; set; } // rowguid (Primary key)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate (Primary key)
        public VAdditionalContactInfo()
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
