// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vEmployee
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VEmployee
    {
        public int? BusinessEntityId { get; set; } // BusinessEntityID (Primary key)
        public string Title { get; set; } // Title (length: 8)
        public string FirstName { get; set; } // FirstName (Primary key) (length: 50)
        public string MiddleName { get; set; } // MiddleName (length: 50)
        public string LastName { get; set; } // LastName (Primary key) (length: 50)
        public string Suffix { get; set; } // Suffix (length: 10)
        public string JobTitle { get; set; } // JobTitle (Primary key) (length: 50)
        public string PhoneNumber { get; set; } // PhoneNumber (length: 25)
        public string PhoneNumberType { get; set; } // PhoneNumberType (length: 50)
        public string EmailAddress { get; set; } // EmailAddress (length: 50)
        public int? EmailPromotion { get; set; } // EmailPromotion (Primary key)
        public string AddressLine1 { get; set; } // AddressLine1 (Primary key) (length: 60)
        public string AddressLine2 { get; set; } // AddressLine2 (length: 60)
        public string City { get; set; } // City (Primary key) (length: 30)
        public string StateProvinceName { get; set; } // StateProvinceName (Primary key) (length: 50)
        public string PostalCode { get; set; } // PostalCode (Primary key) (length: 15)
        public string CountryRegionName { get; set; } // CountryRegionName (Primary key) (length: 50)
        public string AdditionalContactInfo { get; set; } // AdditionalContactInfo
        public VEmployee()
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
