// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vJobCandidateEducation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VJobCandidateEducation
    {
        public int? JobCandidateId { get; set; } // JobCandidateID (Primary key)
        public string Edu46Level { get; set; } // Edu.Level
        public System.DateTime? Edu46StartDate { get; set; } // Edu.StartDate
        public System.DateTime? Edu46EndDate { get; set; } // Edu.EndDate
        public string Edu46Degree { get; set; } // Edu.Degree (length: 50)
        public string Edu46Major { get; set; } // Edu.Major (length: 50)
        public string Edu46Minor { get; set; } // Edu.Minor (length: 50)
        public string Edu46Gpa { get; set; } // Edu.GPA (length: 5)
        public string Edu46GpaScale { get; set; } // Edu.GPAScale (length: 5)
        public string Edu46School { get; set; } // Edu.School (length: 100)
        public string Edu46Loc46CountryRegion { get; set; } // Edu.Loc.CountryRegion (length: 100)
        public string Edu46Loc46State { get; set; } // Edu.Loc.State (length: 100)
        public string Edu46Loc46City { get; set; } // Edu.Loc.City (length: 100)
        public VJobCandidateEducation()
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
