// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vJobCandidate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VJobCandidate
    {
        public int? JobCandidateId { get; set; } // JobCandidateID (Primary key)
        public int? BusinessEntityId { get; set; } // BusinessEntityID
        public string Name46Prefix { get; set; } // Name.Prefix (length: 30)
        public string Name46First { get; set; } // Name.First (length: 30)
        public string Name46Middle { get; set; } // Name.Middle (length: 30)
        public string Name46Last { get; set; } // Name.Last (length: 30)
        public string Name46Suffix { get; set; } // Name.Suffix (length: 30)
        public string Skills { get; set; } // Skills
        public string Addr46Type { get; set; } // Addr.Type (length: 30)
        public string Addr46Loc46CountryRegion { get; set; } // Addr.Loc.CountryRegion (length: 100)
        public string Addr46Loc46State { get; set; } // Addr.Loc.State (length: 100)
        public string Addr46Loc46City { get; set; } // Addr.Loc.City (length: 100)
        public string Addr46PostalCode { get; set; } // Addr.PostalCode (length: 20)
        public string EMail { get; set; } // EMail
        public string WebSite { get; set; } // WebSite
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate (Primary key)
        public VJobCandidate()
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
