// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vPersonDemographics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VPersonDemographic
    {
        public int? BusinessEntityId { get; set; } // BusinessEntityID (Primary key)
        public decimal? TotalPurchaseYtd { get; set; } // TotalPurchaseYTD
        public System.DateTime? DateFirstPurchase { get; set; } // DateFirstPurchase
        public System.DateTime? BirthDate { get; set; } // BirthDate
        public string MaritalStatus { get; set; } // MaritalStatus (length: 1)
        public string YearlyIncome { get; set; } // YearlyIncome (length: 30)
        public string Gender { get; set; } // Gender (length: 1)
        public int? TotalChildren { get; set; } // TotalChildren
        public int? NumberChildrenAtHome { get; set; } // NumberChildrenAtHome
        public string Education { get; set; } // Education (length: 30)
        public string Occupation { get; set; } // Occupation (length: 30)
        public bool? HomeOwnerFlag { get; set; } // HomeOwnerFlag
        public int? NumberCarsOwned { get; set; } // NumberCarsOwned
        public VPersonDemographic()
        {
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
