// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.72
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace AdventureWorks.Business.Entities
{

    // vStoreWithDemographics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public partial class VStoreWithDemographicConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VStoreWithDemographic>
    {
        public VStoreWithDemographicConfiguration() : this("Sales")
        {
        }

        public VStoreWithDemographicConfiguration(string schema)
        {
            ToTable("vStoreWithDemographics", schema);
            HasKey(x => new { x.BusinessEntityId, x.Name });

            Property(x => x.BusinessEntityId).HasColumnName(@"BusinessEntityID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AnnualSales).HasColumnName(@"AnnualSales").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.AnnualRevenue).HasColumnName(@"AnnualRevenue").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.BankName).HasColumnName(@"BankName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.BusinessType).HasColumnName(@"BusinessType").HasColumnType("nvarchar").IsOptional().HasMaxLength(5);
            Property(x => x.YearOpened).HasColumnName(@"YearOpened").HasColumnType("int").IsOptional();
            Property(x => x.Specialty).HasColumnName(@"Specialty").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.SquareFeet).HasColumnName(@"SquareFeet").HasColumnType("int").IsOptional();
            Property(x => x.Brands).HasColumnName(@"Brands").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.Internet).HasColumnName(@"Internet").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.NumberEmployees).HasColumnName(@"NumberEmployees").HasColumnType("int").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
